export class Role {
  constructor(public id: number, public name: string, public isRequired: boolean) {}
}

export const roles: Role[] = [
  new Role(1, 'Pizza Quality Specialist', false),
  new Role(2, 'Air Quality Inspector', false),
  new Role(3, 'Card Game Strategist', false),
  new Role(4, 'Substance Consultant', true),
  new Role(5, 'Noodle Quality Analyst', false),
  new Role(6, 'Lighting Consultant', false),
  new Role(7, 'Sky Observer', false),
  new Role(8, 'Humor Advisor', false),
  new Role(9, 'Entrance Ambassador', false),
  new Role(10, 'Cheese Artisan', false),
  new Role(11, 'Inflatable Specialist', false),
  new Role(12, 'Glass Care Specialist', false),
  new Role(13, 'Sleep Strategist', false),
  new Role(14, 'Oral Hygiene Consultant', false),
  new Role(15, 'Ergonomic Specialist', false),
  new Role(16, 'Financial Analyst', false),
  new Role(17, 'Bubble Wrap Technician', false),
  new Role(18, 'Tea Temperature Expert', false),
  new Role(19, 'Cookie Integrity Analyst', false),
  new Role(20, 'Professional Cloud Spotter', false),
  new Role(21, 'Color Harmony Specialist', false),
  new Role(22, 'Meme Curator', false),
  new Role(23, 'Digital Nomad Advisor', false),
  new Role(24, 'Emoji Interpreter', false),
  new Role(25, 'Chief Snack Officer', false),
  new Role(26, 'Head of Comfort Operations', false),
  new Role(27, 'Ambient Sound Consultant', false),
  new Role(28, 'Mood Lighting Designer', false),
  new Role(29, 'Sneaker Hygiene Specialist', false),
  new Role(30, 'Nap Optimization Expert', false),
  new Role(31, 'Jargon Translator', false),
  new Role(32, 'Chief Caffeine Strategist', false),
  new Role(33, 'Plant Communication Specialist', false),
  new Role(34, 'Office Zen Master', false),
  new Role(35, 'Sandwich Architect', false),
  new Role(36, 'Virtual Background Designer', false),
  new Role(37, 'Ice Cream Quality Tester', false),
  new Role(38, 'Social Media Detox Coach', false),
  new Role(39, 'Pillow Comfort Analyst', false),
  new Role(40, 'Wi-Fi Stability Inspector', false),
  new Role(41, 'Acoustic Vibe Consultant', false),
  new Role(42, 'Pet Socialization Coordinator', false),
  new Role(43, 'Traffic Flow Analyst', false),
  new Role(44, 'Desk Ergonomics Advisor', false),
  new Role(45, 'Cupcake Evaluation Specialist', false),
  new Role(46, 'Handwriting Analyst', false),
  new Role(47, 'Pixel Arrangement Supervisor', false),
  new Role(48, 'Gadget Affinity Tester', false),
  new Role(49, 'Digital Wellbeing Facilitator', false),
  new Role(50, 'Personal Space Consultant', false),
  new Role(51, 'Sleep Cycle Synchronizer', false),
  new Role(52, 'Paper Clip Efficiency Engineer', false),
  new Role(53, 'Hologram Specialist', false),
  new Role(54, 'Sushi Presentation Analyst', false),
  new Role(55, 'Feng Shui Evaluator', false),
  new Role(56, 'Hot Sauce Tester', false),
  new Role(57, 'Board Game Enthusiast', false),
  new Role(58, 'E-Sports Consultant', false),
  new Role(59, 'Furniture Placement Specialist', false),
  new Role(60, 'Signature Authenticity Inspector', false),
  new Role(61, 'Emoji Impact Researcher', false),
  new Role(62, 'Parallel Parking Instructor', false),
  new Role(63, 'Surreal Art Connoisseur', false),
  new Role(64, 'High-Five Coordinator', false),
  new Role(65, 'Mood Enhancement Specialist', false),
  new Role(66, 'Eco-Friendly Product Advisor', false),
  new Role(67, 'Tropical Fruit Consultant', false),
  new Role(68, 'Gadget Recycling Strategist', false),
  new Role(69, 'Vintage Vinyl Selector', false),
  new Role(70, 'Puzzle Complexity Analyst', false),
  new Role(71, 'Secret Handshake Developer', false),
  new Role(72, 'Balloon Animal Engineer', false),
  new Role(73, 'Digital Time Traveler', false),
  new Role(74, 'Puddle Splashing Expert', false),
  new Role(75, 'Cereal-to-Milk Ratio Specialist', false),
  new Role(76, 'Fireplace Ambiance Coordinator', false),
  new Role(77, 'Sand Castle Architect', false),
  new Role(78, 'Chili Pepper Rating Analyst', false),
  new Role(79, 'Handcrafted Soap Evaluator', false),
  new Role(80, 'Sunset Appreciation Guide', false),
  new Role(81, 'Digital Detox Strategist', false),
  new Role(82, 'Storytelling Coach', false),
  new Role(83, 'Soundwave Interpreter', false),
  new Role(84, 'Festival Energy Manager', false),
  new Role(85, 'Social Synchronization Specialist', false),
  new Role(86, 'Daydreaming Facilitator', false),
  new Role(87, 'Cold Brew Calibration Expert', false),
  new Role(88, 'Library Whisperer', false),
  new Role(89, 'Guitar String Resonance Analyst', false),
  new Role(90, 'Ceramic Pottery Evaluator', false),
  new Role(91, 'Aroma Experience Specialist', false),
  new Role(92, 'Minimalism Consultant', false),
  new Role(93, 'Urban Wildlife Observer', false),
  new Role(94, 'Origami Design Coordinator', false),
  new Role(95, 'Bubble Tea Consistency Tester', false),
  new Role(96, 'Internet Rabbit Hole Navigator', false),
  new Role(97, 'Casual Stroll Director', false),
  new Role(98, 'Sustainable Clothing Advisor', false),
  new Role(99, 'Gourmet Popcorn Analyst', false),
  new Role(100, 'Lawn Ornament Strategist', false),
  new Role(101, 'Book Cover Aesthetics Reviewer', false),
  new Role(102, 'Hot Chocolate Foam Inspector', false),
  new Role(103, 'Inspirational Quote Specialist', false),
  new Role(104, 'Board Game Expansion Consultant', false),
  new Role(105, 'Shoelace Tying Efficiency Expert', false),
  new Role(106, 'Garden Path Designer', false),
  new Role(107, 'Candle Scent Curator', false),
  new Role(108, 'Nostalgia Preservationist', false),
  new Role(109, 'Handmade Scarf Inspector', false),
  new Role(110, 'Ecosystem Connectivity Analyst', false),
  new Role(111, 'Cardboard Box Structural Engineer', false),
  new Role(112, 'Cozy Atmosphere Facilitator', false),
  new Role(113, 'DIY Home Project Coach', false),
  new Role(114, 'Backyard Astronomy Guide', false),
  new Role(115, 'Laundry Folding Strategist', false),
  new Role(116, 'Farmers Market Analyst', false),
  new Role(117, 'Houseplant Whisperer', false),
  new Role(118, 'Lemonade Sweetness Balancer', false),
  new Role(119, 'Seasonal Wardrobe Coordinator', false),
  new Role(120, 'Icebreaker Question Curator', false),
  new Role(121, 'Bonsai Tree Therapist', false),
  new Role(122, 'Historical Fiction Fact-Checker', false),
  new Role(123, 'Scent Memory Researcher', false),
  new Role(124, 'Personalized Gift Consultant', false),
  new Role(125, 'Pencil Sharpening Technician', false),
  new Role(126, 'Postcard Design Specialist', false),
  new Role(127, 'Festival Booth Aesthetic Director', false),
  new Role(128, 'Doodle Interpretation Analyst', false),
  new Role(129, 'Accent Imitation Expert', false),
  new Role(130, 'Music Playlist Curator', false),
  new Role(131, 'Puzzle Piece Alignment Specialist', false),
  new Role(132, 'Luxury Bubble Bath Consultant', false),
  new Role(133, 'Gourmet Toast Specialist', false),
  new Role(134, 'Artisanal Candle Maker', false),
  new Role(135, 'Picnic Optimization Expert', false),
  new Role(136, 'Comfort Food Critic', false),
  new Role(137, 'Handmade Craft Promoter', false),
  new Role(138, 'Ice Skating Elegance Advisor', false),
  new Role(139, 'Festival Costume Coordinator', false),
  new Role(140, 'DIY Project Troubleshooter', false),
  new Role(141, 'Kitchen Gadget Experimenter', false),
  new Role(142, 'Natural Light Coordinator', false),
  new Role(143, 'Outdoor Hammock Tester', false),
  new Role(144, 'Theater Seat Comfort Analyst', false),
  new Role(145, 'Sunglasses Style Consultant', false),
  new Role(146, 'Seasonal Beverage Expert', false),
  new Role(147, 'Cheesecake Texture Evaluator', false),
  new Role(148, 'Tactile Experience Specialist', false),
  new Role(149, 'Soundtrack Experience Curator', false),
  new Role(150, 'Joyful Experience Engineer', false),
  new Role(151, 'Handwriting Style Advisor', false),
  new Role(152, 'Cup Holder Logistics Coordinator', false),
  new Role(153, 'Social Awkwardness Mitigator', false),
  new Role(154, 'Urban Graffiti Analyst', false),
  new Role(155, 'Secret Passage Finder', false),
  new Role(156, 'Surprise Party Strategist', false),
  new Role(157, 'Digital Ghost Hunter', false),
  new Role(158, 'Zen Garden Maintainer', false),
  new Role(159, 'Minimalist Decor Consultant', false),
  new Role(160, 'Late-Night Thought Collector', false),
  new Role(161, 'Coffee Stirring Technique Evaluator', false),
  new Role(162, 'Library Aisle Wanderer', false),
  new Role(163, 'Distant Star Cataloger', false),
  new Role(164, 'Spicy Food Endurance Coach', false),
  new Role(165, 'Campfire Story Facilitator', false),
  new Role(166, 'Urban Exploration Guide', false),
  new Role(167, 'Sunbeam Enjoyment Advisor', false),
  new Role(168, 'DIY Candle Wax Sculptor', false),
  new Role(169, 'Music Lyric Analyst', false),
  new Role(170, 'Keyboard Sound Tester', false),
  new Role(171, 'Elderly Story Collector', false),
  new Role(172, 'Whistle Tone Researcher', false),
  new Role(173, 'Scenic Route Planner', false),
  new Role(174, 'Whimsical Idea Generator', false),
  new Role(175, 'Echo Acoustics Engineer', false)
];
